export const BIBLE_CODE_MAPPER = {
  1: { name: '창세기', shortName: '창', chapterCnt: 50, enName: 'Genesis' },
  2: { name: '출애굽기', shortName: '출', chapterCnt: 40, enName: 'Exodus' },
  3: { name: '레위기', shortName: '레', chapterCnt: 27, enName: 'Leviticus' },
  4: { name: '민수기', shortName: '민', chapterCnt: 36, enName: 'Numbers' },
  5: { name: '신명기', shortName: '신', chapterCnt: 34, enName: 'Deuteronomy' },
  6: { name: '여호수아', shortName: '수', chapterCnt: 24, enName: 'Joshua' },
  7: { name: '사사기', shortName: '삿', chapterCnt: 21, enName: 'Judges' },
  8: { name: '룻기', shortName: '룻', chapterCnt: 4, enName: 'Ruth' },
  9: { name: '사무엘상', shortName: '삼상', chapterCnt: 31, enName: 'I_Samuel' },
  10: { name: '사무엘하', shortName: '삼하', chapterCnt: 24, enName: 'II_Samuel' },
  11: { name: '열왕기상', shortName: '왕상', chapterCnt: 22, enName: 'I_Kings' },
  12: { name: '열왕기하', shortName: '왕하', chapterCnt: 25, enName: 'II_kings' },
  13: { name: '역대상', shortName: '대상', chapterCnt: 29, enName: 'I_Chronicles' },
  14: { name: '역대하', shortName: '대하', chapterCnt: 36, enName: 'II_Chronicles' },
  15: { name: '에스라', shortName: '스', chapterCnt: 10, enName: 'Ezra' },
  16: { name: '느헤미야', shortName: '느', chapterCnt: 13, enName: 'Nehemiah' },
  17: { name: '에스더', shortName: '에', chapterCnt: 10, enName: 'Esther' },
  18: { name: '욥기', shortName: '욥', chapterCnt: 42, enName: 'Job' },
  19: { name: '시편', shortName: '시', chapterCnt: 150, enName: 'Psalms' },
  20: { name: '잠언', shortName: '잠', chapterCnt: 31, enName: 'Proverbs' },
  21: { name: '전도서', shortName: '전', chapterCnt: 12, enName: 'Ecclesiastes' },
  22: { name: '아가', shortName: '아', chapterCnt: 8, enName: 'Song_of_Songs' },
  23: { name: '이사야', shortName: '사', chapterCnt: 66, enName: 'Isaiah' },
  24: { name: '예레미야', shortName: '렘', chapterCnt: 52, enName: 'Jeremiah' },
  25: { name: '예레미야애가', shortName: '애', chapterCnt: 5, enName: 'Lamentations' },
  26: { name: '에스겔', shortName: '겔', chapterCnt: 48, enName: 'Ezekiel' },
  27: { name: '다니엘', shortName: '단', chapterCnt: 12, enName: 'Daniel' },
  28: { name: '호세아', shortName: '호', chapterCnt: 14, enName: 'Hosea' },
  29: { name: '요엘', shortName: '욜', chapterCnt: 3, enName: 'Joel' },
  30: { name: '아모스', shortName: '암', chapterCnt: 9, enName: 'Amos' },
  31: { name: '오바댜', shortName: '옵', chapterCnt: 1, enName: 'Obadiah' },
  32: { name: '요나', shortName: '욘', chapterCnt: 4, enName: 'Jonah' },
  33: { name: '미가', shortName: '미', chapterCnt: 7, enName: 'Micah' },
  34: { name: '나훔', shortName: '나', chapterCnt: 3, enName: 'Nahum' },
  35: { name: '하박국', shortName: '합', chapterCnt: 3, enName: 'Habakkuk' },
  36: { name: '스바냐', shortName: '습', chapterCnt: 3, enName: 'Zephariah' },
  37: { name: '학개', shortName: '학', chapterCnt: 2, enName: 'Haggai' },
  38: { name: '스가랴', shortName: '슥', chapterCnt: 14, enName: 'Zechariah' },
  39: { name: '말라기', shortName: '말', chapterCnt: 4, enName: 'Malachi' },
  40: { name: '마태복음', shortName: '마', chapterCnt: 28, enName: 'Matthew' },
  41: { name: '마가복음', shortName: '막', chapterCnt: 16, enName: 'Mark' },
  42: { name: '누가복음', shortName: '눅', chapterCnt: 24, enName: 'Luke' },
  43: { name: '요한복음', shortName: '요', chapterCnt: 21, enName: 'John' },
  44: { name: '사도행전', shortName: '행', chapterCnt: 28, enName: 'Acts' },
  45: { name: '로마서', shortName: '롬', chapterCnt: 16, enName: 'Romans' },
  46: { name: '고린도전서', shortName: '고전', chapterCnt: 16, enName: 'Corinthians 1' },
  47: { name: '고린도후서', shortName: '고후', chapterCnt: 13, enName: 'Corinthians 2' },
  48: { name: '갈라디아서', shortName: '갈', chapterCnt: 6, enName: 'Galatians' },
  49: { name: '에베소서', shortName: '엡', chapterCnt: 6, enName: 'Ephesians' },
  50: { name: '빌립보서', shortName: '빌', chapterCnt: 4, enName: 'Philippians' },
  51: { name: '골로새서', shortName: '골', chapterCnt: 4, enName: 'Colossians' },
  52: { name: '데살로니가전서', shortName: '살전', chapterCnt: 5, enName: 'Thessalonians 1' },
  53: { name: '데살로니가후서', shortName: '살후', chapterCnt: 3, enName: 'Thessalonians 2' },
  54: { name: '디모데전서', shortName: '딤전', chapterCnt: 6, enName: 'Timothy 1' },
  55: { name: '디모데후서', shortName: '딤후', chapterCnt: 4, enName: 'Timothy 2' },
  56: { name: '디도서', shortName: '딛', chapterCnt: 3, enName: 'Titus' },
  57: { name: '빌레몬서', shortName: '몬', chapterCnt: 1, enName: 'Philemon' },
  58: { name: '히브리서', shortName: '히', chapterCnt: 13, enName: 'Hebrews' },
  59: { name: '야고보서', shortName: '약', chapterCnt: 5, enName: 'James' },
  60: { name: '베드로전서', shortName: '벧전', chapterCnt: 5, enName: 'Peter 1' },
  61: { name: '베드로후서', shortName: '벧후', chapterCnt: 3, enName: 'Peter 2' },
  62: { name: '요한일서', shortName: '요일', chapterCnt: 5, enName: 'John 1' },
  63: { name: '요한이서', shortName: '요이', chapterCnt: 1, enName: 'John 2' },
  64: { name: '요한삼서', shortName: '요삼', chapterCnt: 1, enName: 'John 3' },
  65: { name: '유다서', shortName: '유', chapterCnt: 1, enName: 'Jude' },
  66: { name: '요한계시록', shortName: '계', chapterCnt: 22, enName: 'Revelation' },
};
